module.exports = [
  'Everything',
  'Gifts',
  'Videos',
  'Animals & pets',
  'Architecture',
  'Art',
  'Cars & motorcycles',
  'Celebrations & events',
  'Celebritries',
  'DIY & crafts',
  'Design',
  'Education',
  'Entertainment',
  'Food and drink',
  'Gardening',
  'Geek',
  'Hair & beauty',
  'Health & fitness',
  'History',
  'Home decor',
  'Humour',
  'Illustrations & posters',
  'Kids & parenting',
  "Men's fashion",
  'Outdoors',
  'Photography',
  'Products',
  'Quotes',
  'Science & nature',
  'Sport',
  'Tattoos',
  'Technology',
  'Travel',
  'Weddings',
  "Women's fashion"
];
